version: "3.7"
services:
  
  users_db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      
  users:
    build:
      context: ./users
    expose:
      - "5000"
    environment:
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:users.docker.localhost,traefik.backend=users,traefik.backend.circuitbreaker.expression=NetworkErrorRatio()>0.5
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - rabbitmq
      - users_db


volumes:
  users_data:
